"""Immutable foundational runtime models for Vitrine."""

from .audiences import AudienceContext
from .candidates import (
    CandidateAvailabilityObservation,
    CandidateEvaluation,
    CandidateSourceEndpoint,
    PortfolioCandidate,
)
from .conversion import (
    RECORD_TYPE_REGISTRY,
    VitrineRecord,
    record_from_dict,
    record_to_dict,
)
from .curation import (
    PlacementPresentation,
    PortfolioPlacement,
    PortfolioSelection,
    SectionArrangementRevision,
    WorkingPortfolioCompositionRevision,
)
from .errors import (
    ValidationIssue,
    VitrineModelError,
    VitrineModelValidationError,
    VitrineRecordGraphError,
    VitrineSerializationError,
)
from .graph import (
    VitrineRecordGraph,
    collect_record_graph_issues,
    validate_record_graph,
)
from .identity import (
    ActorAttribution,
    ClassQualifiedStudentRef,
    CompositionRevisionRef,
    DigestReference,
    Portfolio,
    PortfolioSubject,
    PortfolioSubjectClassLink,
    ProfileRevisionRef,
    SnapshotEditionRef,
    VitrineRecordRef,
)
from .profiles import (
    PortfolioProfileBinding,
    PortfolioProfileFamily,
    PortfolioProfileRevision,
    ProfileApplicability,
    ProfileAudienceRule,
    ProfileSectionDefinition,
)
from .serialization import (
    graph_from_dict,
    graph_from_json_bytes,
    graph_to_canonical_json_bytes,
    graph_to_dict,
    record_from_json_bytes,
    record_to_canonical_json_bytes,
    strict_json_loads,
)
from .snapshots import (
    SnapshotEdition,
    SnapshotEntry,
    SnapshotManifest,
    SnapshotMaterializationRecord,
    SnapshotOmission,
    SnapshotSeal,
)
from .sources import (
    AcademicWorkRegistrationSnapshot,
    CorePublicationSourceReference,
    PortfolioSubjectRelationshipAssertion,
    ProducerSourceReference,
    SourceArtifactReference,
    SourcePrivacyMetadata,
)

__all__ = [
    "AcademicWorkRegistrationSnapshot",
    "ActorAttribution",
    "AudienceContext",
    "CandidateAvailabilityObservation",
    "CandidateEvaluation",
    "CandidateSourceEndpoint",
    "ClassQualifiedStudentRef",
    "CompositionRevisionRef",
    "CorePublicationSourceReference",
    "DigestReference",
    "PlacementPresentation",
    "Portfolio",
    "PortfolioCandidate",
    "PortfolioPlacement",
    "PortfolioProfileBinding",
    "PortfolioProfileFamily",
    "PortfolioProfileRevision",
    "PortfolioSelection",
    "PortfolioSubject",
    "PortfolioSubjectClassLink",
    "PortfolioSubjectRelationshipAssertion",
    "ProducerSourceReference",
    "ProfileApplicability",
    "ProfileAudienceRule",
    "ProfileRevisionRef",
    "ProfileSectionDefinition",
    "RECORD_TYPE_REGISTRY",
    "SectionArrangementRevision",
    "SnapshotEdition",
    "SnapshotEditionRef",
    "SnapshotEntry",
    "SnapshotManifest",
    "SnapshotMaterializationRecord",
    "SnapshotOmission",
    "SnapshotSeal",
    "SourceArtifactReference",
    "SourcePrivacyMetadata",
    "ValidationIssue",
    "VitrineModelError",
    "VitrineModelValidationError",
    "VitrineRecord",
    "VitrineRecordGraph",
    "VitrineRecordGraphError",
    "VitrineRecordRef",
    "VitrineSerializationError",
    "WorkingPortfolioCompositionRevision",
    "collect_record_graph_issues",
    "graph_from_dict",
    "graph_from_json_bytes",
    "graph_to_canonical_json_bytes",
    "graph_to_dict",
    "record_from_dict",
    "record_from_json_bytes",
    "record_to_canonical_json_bytes",
    "record_to_dict",
    "strict_json_loads",
    "validate_record_graph",
]
